name: Publish Docker Images

on:
  push:
    branches:
      - stable
      - dev
    tags:
      - '*'

jobs:
  push_to_registry:
    name: Push Docker images to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Publish dev as dev to docker.io registry
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: aflplusplus/aflplusplus:${{ github.ref_name }}
        if: ${{ github.ref_name == 'dev' }}
      - name: Publish stable as stable and latest to docker.io registry
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: aflplusplus/aflplusplus:${{ github.ref_name }},aflplusplus/aflplusplus:latest
        if: ${{ github.ref_name == 'stable' }}
      - name: Publish tagged release to docker.io registry
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: aflplusplus/aflplusplus:${{ github.ref_name }}
        if: ${{ github.ref_type == 'tag' }}
